#!/usr/bin/env bash
set -euo pipefail

# check-drift.sh — Compare containment directory against workspace root
#
# Reports what's changed, added, missing, and unchanged between the
# containment directory (template source of truth) and the workspace root.
#
# File categories:
#   Rendered     — Dual-owned files rendered by tools/render-instructions.sh
#                  (expected to differ; containment has {{{tokens}}}, root has values)
#   Unchanged    — Containment = root (byte-for-byte match)
#   Modified     — Consumer modified a template-owned file
#   Not adopted  — In containment but not at root (new upstream content)
#   Consumer-owned — At root but not in containment (consumer-created files)
#
# Usage:
#   tools/check-drift.sh           # Summary view
#   tools/check-drift.sh --verbose  # Show diffs for modified files
#
# Exit codes:
#   0 — Check completed (even if drift found)
#   1 — Error (no containment dir, etc.)
#
# Issue #38: Drift detection and guided update adoption

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ── Detect containment directory ───────────────────────────────
CONTAINMENT_DIR=""
for dir in "$WORKSPACE_DIR"/.workspace-*; do
  if [[ -d "$dir" ]]; then
    CONTAINMENT_DIR="$(basename "$dir")"
    break
  fi
done

if [[ -z "$CONTAINMENT_DIR" ]]; then
  echo -e "${RED}❌ No containment directory found (expected .workspace-*/ at workspace root)${NC}"
  exit 1
fi

# ── Parse arguments ────────────────────────────────────────────
VERBOSE=false
for arg in "$@"; do
  case "$arg" in
    --verbose|-v) VERBOSE=true ;;
    -h|--help)
      echo "Usage: tools/check-drift.sh [--verbose]"
      echo ""
      echo "Compare containment directory (${CONTAINMENT_DIR}/) against workspace root."
      echo ""
      echo "Options:"
      echo "  --verbose, -v   Show diffs for modified files"
      echo "  --help, -h      Show this help message"
      echo ""
      echo "This is a non-destructive read-only comparison."
      exit 0
      ;;
    *) echo -e "${RED}Unknown argument: $arg${NC}"; exit 1 ;;
  esac
done

cd "$WORKSPACE_DIR"

# ── Constants ──────────────────────────────────────────────────

# Files that only exist in containment (never copied to root)
CONTAINMENT_ONLY=(
  "initialize-workspace.sh"
  ".template.yaml"
  "tools/copy-template.sh"
)

# Rendered file marker (set by render-instructions.sh)
RENDERED_MARKER="GENERATED by tools/render-instructions.sh"

# ── Helpers ────────────────────────────────────────────────────

is_containment_only() {
  local rel_path="$1"
  for excluded in "${CONTAINMENT_ONLY[@]}"; do
    if [[ "$rel_path" == "$excluded" ]]; then
      return 0
    fi
  done
  return 1
}

is_rendered_file() {
  local root_file="$1"
  if [[ -f "$root_file" ]] && head -5 "$root_file" | grep -q "$RENDERED_MARKER" 2>/dev/null; then
    return 0
  fi
  return 1
}

is_binary() {
  local file="$1"
  if file --brief --mime "$file" 2>/dev/null | grep -qv "text/"; then
    return 0
  fi
  return 1
}

# ── Scan containment ──────────────────────────────────────────

echo -e "${BOLD}Drift Report${NC}"
echo -e "${DIM}Containment: ${CONTAINMENT_DIR}/${NC}"
echo ""

# Counters
COUNT_UNCHANGED=0
COUNT_RENDERED=0
COUNT_MODIFIED=0
COUNT_NOT_ADOPTED=0
COUNT_EXCLUDED=0

# Collect modified files for verbose output
MODIFIED_FILES=()

# Process each file in containment
while IFS= read -r containment_file; do
  # Get path relative to containment dir
  rel_path="${containment_file#"$CONTAINMENT_DIR"/}"
  root_file="$rel_path"

  # Skip containment-only files
  if is_containment_only "$rel_path"; then
    COUNT_EXCLUDED=$((COUNT_EXCLUDED + 1))
    continue
  fi

  # Check if root file exists
  if [[ ! -e "$root_file" ]]; then
    COUNT_NOT_ADOPTED=$((COUNT_NOT_ADOPTED + 1))
    echo -e "  ${BLUE}+ not adopted${NC}  $rel_path"
    continue
  fi

  # Check if it's a rendered file (expected drift)
  if is_rendered_file "$root_file"; then
    COUNT_RENDERED=$((COUNT_RENDERED + 1))
    continue
  fi

  # Compare files
  if is_binary "$containment_file"; then
    # Binary comparison
    if cmp -s "$containment_file" "$root_file"; then
      COUNT_UNCHANGED=$((COUNT_UNCHANGED + 1))
    else
      COUNT_MODIFIED=$((COUNT_MODIFIED + 1))
      MODIFIED_FILES+=("$rel_path")
      echo -e "  ${YELLOW}~ modified${NC}     $rel_path"
    fi
  else
    # Text comparison
    if diff -q "$containment_file" "$root_file" &>/dev/null; then
      COUNT_UNCHANGED=$((COUNT_UNCHANGED + 1))
    else
      COUNT_MODIFIED=$((COUNT_MODIFIED + 1))
      MODIFIED_FILES+=("$rel_path")
      echo -e "  ${YELLOW}~ modified${NC}     $rel_path"
    fi
  fi

done < <(find "$CONTAINMENT_DIR" -type f | sort | sed "s|^\./||")

# ── Scan root for consumer-owned files ─────────────────────────
# Files at root that don't have a containment counterpart

COUNT_CONSUMER=0

# Directories to skip when scanning root
SKIP_DIRS=".git|${CONTAINMENT_DIR}|repos|.tmp|node_modules|.DS_Store"

while IFS= read -r root_file; do
  rel_path="${root_file#./}"
  containment_file="${CONTAINMENT_DIR}/${rel_path}"

  if [[ ! -e "$containment_file" ]]; then
    COUNT_CONSUMER=$((COUNT_CONSUMER + 1))
    if [[ "$VERBOSE" == true ]]; then
      echo -e "  ${CYAN}◆ consumer${NC}     $rel_path"
    fi
  fi
done < <(find . -type f \
  -not -path "./.git/*" \
  -not -path "./${CONTAINMENT_DIR}/*" \
  -not -path "./repos/*" \
  -not -path "./.tmp/*" \
  -not -name ".DS_Store" \
  | sort)

# ── Summary ────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}DRIFT SUMMARY${NC}"
echo -e "${BOLD}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${GREEN}✓ Unchanged:${NC}     $COUNT_UNCHANGED file(s)"
echo -e "  ${GREEN}✓ Rendered:${NC}      $COUNT_RENDERED file(s)  ${DIM}(dual-owned, expected drift)${NC}"
echo -e "  ${YELLOW}~ Modified:${NC}      $COUNT_MODIFIED file(s)  ${DIM}(consumer changed template file)${NC}"
echo -e "  ${BLUE}+ Not adopted:${NC}   $COUNT_NOT_ADOPTED file(s)  ${DIM}(in containment, not at root)${NC}"
echo -e "  ${CYAN}◆ Consumer-owned:${NC} $COUNT_CONSUMER file(s)  ${DIM}(at root, not in containment)${NC}"
echo -e "  ${DIM}  Excluded:${NC}      $COUNT_EXCLUDED file(s)  ${DIM}(containment-only)${NC}"
echo ""

# ── Guidance ───────────────────────────────────────────────────

if [[ $COUNT_NOT_ADOPTED -gt 0 ]]; then
  echo -e "${YELLOW}Action needed:${NC} $COUNT_NOT_ADOPTED file(s) not yet adopted from containment."
  echo "  Run: .${CONTAINMENT_DIR}/tools/copy-template.sh"
  echo ""
fi

if [[ $COUNT_MODIFIED -gt 0 ]]; then
  echo -e "${YELLOW}Review needed:${NC} $COUNT_MODIFIED file(s) modified from template defaults."
  echo "  These may be intentional customizations or stale divergences."
  if [[ "$VERBOSE" != true ]]; then
    echo "  Run with --verbose to see diffs."
  fi
  echo ""
fi

if [[ $COUNT_MODIFIED -eq 0 && $COUNT_NOT_ADOPTED -eq 0 ]]; then
  echo -e "${GREEN}✅ No drift detected — workspace matches containment.${NC}"
  echo ""
fi

# ── Verbose diffs ──────────────────────────────────────────────

if [[ "$VERBOSE" == true && ${#MODIFIED_FILES[@]} -gt 0 ]]; then
  echo -e "${BOLD}Modified file diffs:${NC}"
  echo ""
  for rel_path in "${MODIFIED_FILES[@]}"; do
    echo -e "${BOLD}── $rel_path ──${NC}"
    diff --color=auto "${CONTAINMENT_DIR}/${rel_path}" "$rel_path" || true
    echo ""
  done
fi
